### ISSUE TITLE
What parameters did you use for generation from scratch?

### ISSUE THREAD

**Issue by RostislavKorst** [sndnyang/JEMPP#1]
Hi!

Could you tell me, what parameters (n_steps and in_steps) did you use for generation from scratch with your checkpoints jempp_M10.pt? In README you showed gif file that demonstrates from scratch generation, but i couldn't find parameters of it in the paper.

Thank you for your interesting paper!

**Comment by sndnyang** [comment]
Hi, sorry for the late response.

You may try

python eval_jempp.py --eval uncond_samples --n_steps 10 --in_steps 5 --n_sample_steps 1000  --in_lr 0.2 --sgld_std 0 --reinit_freq 0 --batch_size 100 --buffer_size 100 --load_path ./jempp_M10.pt  --print_every 1 --sgld_lr 0

or

python eval_jempp.py --eval uncond_samples --n_steps 100 --in_steps 5 --n_sample_steps 1000  --in_lr 0.01 --sgld_std 0 --reinit_freq 0 --batch_size 100 --buffer_size 100 --load_path ./jempp_M10.pt  --print_every 1 --sgld_lr 1

I just verified that both can work.

Note: Keep the model  in train status, which means that don't use model.eval().

**Comment by RostislavKorst** [comment]
Hi!

I tried this expressions but it doesn't work for me with code in eval_jempp.py
Maybe code in this file a bit outdated? I got: TypeError: sample_q() got an unexpected keyword argument 'i'

Thank you for your response!

**Comment by sndnyang** [comment]
I got it.  And I solve the inconsistency caused by my several folders.  I update the file with a new comment. Please check it.

BTW, the better generation can use this one:

python eval_jempp.py --eval uncond_samples --n_steps 10  --n_sample_steps 1000    --sgld_std 0 --reinit_freq 0 --batch_size 100 --buffer_size 100 --load_path ./jempp_M10.pt  --print_every 1 --sgld_lr 1  --in_lr 0 --in_steps 0

**Comment by RostislavKorst** [comment]
It works! Thank you!
